services:
  - type: web
    name: music-masive-download-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: YTDLP_PATH
        value: /usr/local/bin/yt-dlp
      - key: YOUTUBE_COOKIES_B64
        sync: false
      - key: FRONTEND_URL
        sync: false
    plan: free
    healthCheckPath: /api/health